/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7979b08b-3726-4087-8b83-21e963d1ab1c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Zrxh2UcmW",
    "aws_user_pools_web_client_id": "6upq72lb3358l5j93lsg2ogbs7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://denbiljrxbellnjbieuscquwgi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
